version: 2.1

executors:
  shellcheck-executor:
    docker:
      - image: opennms/shellcheck:0.5.0-b3

jobs:
  code-check:
    executor: shellcheck-executor
    steps:
      - checkout
      - run:
          name: Shellcheck Scripts
          command: |
            find . -type f -name '*.sh' | wc -l
            find . -type f -name '*.sh' | xargs shellcheck --external-sources -e SC2129,SC2001,SC2013

workflows:
  test:
    jobs:
      - code-check
